resource "azurerm_public_ip" "nat_pip" {
  name                = "${var.name}-pip"
  location            = var.location
  resource_group_name = var.resource_group_name
  allocation_method   = "Static"
  sku                 = "Standard"
  tags                = var.tags
}

resource "azurerm_nat_gateway" "nat_gw" {
  name                = var.name
  location            = var.location
  resource_group_name = var.resource_group_name
  sku_name            = "Standard"
  tags                = var.tags
}

resource "azurerm_nat_gateway_public_ip_association" "nat_pip_assoc" {
  nat_gateway_id       = azurerm_nat_gateway.nat_gw.id
  public_ip_address_id = azurerm_public_ip.nat_pip.id
}
resource "azurerm_subnet_nat_gateway_association" "nat_assoc" {
  #   for_each       = toset(var.nat_subnets_ids)
  # subnet_id      = each.value
  # var.nat_subnets_ids contains subnet IDs generated by Azure, which are not known until apply time
  # Terraform's for_each requires its keys to be known at plan time
  # ount only needs to know the length of the list at plan time, not the actual ID values.

  count          = length(var.nat_subnets_ids)
  subnet_id      = var.nat_subnets_ids[count.index]
  nat_gateway_id = azurerm_nat_gateway.nat_gw.id
}
