name: Terraform Apply
on:
#   push:
#     branches:
#       - main
  workflow_dispatch:

jobs:
  terraform-apply:
    environment: dev
    permissions:
      contents: read
      packages: read
      id-token: write
    runs-on: ubuntu-latest
    env:
      ARM_USE_OIDC: "true"
      ARM_USE_AZUREAD: "true"
      ARM_CLIENT_ID: ${{vars.OIDC_CLIENT_ID}}
      ARM_TENANT_ID: ${{vars.TENANT_ID}}
      ARM_SUBSCRIPTION_ID: ${{vars.SUBSCRIPTION_ID}}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{vars.OIDC_CLIENT_ID}}
          tenant-id: ${{vars.TENANT_ID}}
          subscription-id: ${{vars.SUBSCRIPTION_ID}}

      - name: Terraform Init
        working-directory: iac\terraform\environments\dev
        shell: bash
            -backend-config="storage_account_name=${{vars.STORAGE_ACCOUNT_NAME}}" \
            -backend-config="container_name=${{vars.STORAGE_CONTAINER_NAME}}" \
            -backend-config="key=${{vars.KEY}}"

      - name: Terraform Plan
        working-directory: iac\terraform\environments\dev
        shell: bash
        # env:
        #   ARM_USE_AZUREAD: "true"
        run: |
          terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: iac\terraform\environments\dev
        shell: bash
        # env:
        #   ARM_USE_AZUREAD: "true"
        run: |
          terraform apply -auto-approve tfplan