name: Terraform Plan
on:
  # pull_request:
  #   branches:
  #     - main
    workflow_dispatch: 
jobs:
  terraform-plan:
    environment: dev # use the dev env >>  var. and secret.
    permissions:
      contents: read
      packages: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{vars.OIDC_CLIENT_ID}}
          tenant-id: ${{vars.TENANT_ID}}
          subscription-id: ${{vars.SUBSCRIPTION_ID}}

      - name: Terraform Init
        working-directory: iac\terraform\environments\dev
        shell: bash
        # env:
        #   ARM_USE_AZUREAD: "true"
        run: |
          terraform init \
            -backend-config="resource_group_name=tfstate-rg" \
            -backend-config="storage_account_name=${{vars.STORAGE_ACCOUNT_NAME}}" \
            -backend-config="container_name=${{vars.STORAGE_CONTAINER_NAME}}" \
            -backend-config="key=${{vars.KEY}}"

      - name: Terraform Plan
        working-directory: iac\terraform\environments\dev
        shell: bash
        # env:
        #   ARM_USE_AZUREAD: "true"
        run: |
          terraform plan -out=tfplan