name: Terraform Plan
on:
  workflow_dispatch:
      inputs:
          target:
              type: environment
              default: dev
permissions:
  id-token: write
  contents: read
  security-events: write
  actions: read
  
jobs:
  tfsec:
    environment: ${{inputs.target}}
    name: tfsec (code scan)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Run tfsec
    
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: iac/terraform/environments/${{ inputs.target }}
          additional_args: >
            --concise-output
            --format sarif
            --out iac/terraform/environments/${{ inputs.target }}/tfsec.sarif
            --minimum-severity HIGH
            --soft-fail

      - name: Upload SARIF (tfsec)
        uses: actions/upload-artifact@v4
        with:
          name: tfsec-results
          path: iac/terraform/environments/${{ inputs.target }}/tfsec.sarif
######################################################################
  checkov:
    environment: ${{inputs.target}}
    name: Checkov (plan scan)
    runs-on: ubuntu-latest
    needs: tfsec
    env:
      TF_IN_AUTOMATION: "true"
      ARM_USE_OIDC: "true"
      ARM_USE_AZUREAD: "true"
      ARM_CLIENT_ID: ${{ vars.OIDC_CLIENT_ID }}
      ARM_TENANT_ID: ${{ vars.TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{vars.OIDC_CLIENT_ID}}
          tenant-id: ${{vars.TENANT_ID}}
          subscription-id: ${{vars.SUBSCRIPTION_ID}}

      - name: Terraform Init
        working-directory: iac/terraform/environments/${{ inputs.target }}
        shell: bash
        # env:
        #   ARM_USE_AZUREAD: "true"
        run: |
          terraform init \
            -backend-config="resource_group_name=${{vars.STORAGE_RG}}" \
            -backend-config="storage_account_name=${{vars.STORAGE_ACCOUNT_NAME}}" \
            -backend-config="container_name=${{vars.STORAGE_CONTAINER_NAME}}" \
            -backend-config="key=${{vars.KEY}}"

      - name: Terraform Plan (json)
        working-directory: iac/terraform/environments/${{ inputs.target }}
        run: terraform plan -out=tfplan.bin && terraform show -json tfplan.bin > tfplan.json

      - name: Run Checkov on plan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: iac/terraform/environments/${{ inputs.target }}
          file: iac/terraform/environments/${{ inputs.target }}/tfplan.json
          framework: terraform_plan
          soft_fail: false
          output_format: sarif
          output_file_path: iac/terraform/environments/${{ inputs.target }}/checkov.sarif

      - name: Upload SARIF (Checkov)
        uses: actions/upload-artifact@v4
        with:
          name: checkov-results
          path: iac/terraform/environments/${{ inputs.target }}/checkov.sarif
